export const COMPONENT_IDS = {
  LIST_STUFF_EDIT: 'list-stuff-edit',
  NAVBAR_ADD_STUFF: 'navbar-add-stuff',
  NAVBAR_LIST_STUFF: 'navbar-list-stuff',
  NAVBAR_LIST_STUFF_ADMIN: 'navbar-list-stuff-admin',
  NAVBAR_CURRENT_USER: 'navbar-current-user',
  NAVBAR_LANDING_PAGE: 'navbar-landing-page',
  NAVBAR_LOGIN_DROPDOWN: 'navbar-login-dropdown',
  NAVBAR_LOGIN_DROPDOWN_SIGN_IN: 'navbar-login-dropdown-sign-in',
  NAVBAR_LOGIN_DROPDOWN_SIGN_UP: 'navbar-login-dropdown-sign-up',
  NAVBAR_HAMBURGER_MENU: 'navbar-hamburger-menu',
  NAVBAR_HAMBURGER_MENU_BROWSE_OPPORTUNITIES: 'navbar-hamburger-menu-browse-opportunities',
  NAVBAR_HAMBURGER_MENU_ORGANIZATION_LIBRARY: 'navbar-hamburger-menu-organization-library',
  NAVBAR_HAMBURGER_MENU_ABOUT_US: 'navbar-hamburger-menu-about-us',
  NAVBAR_USER_HAMBURGER_MENU: 'navbar-user-hamburger-menu',
  NAVBAR_MANAGE_DROPDOWN: 'navbar-manage-dropdown',
  NAVBAR_MANAGE_DROPDOWN_DATABASE: 'navbar-manage-dropdown-database',
  NAVBAR_MY_PROFILE: 'navbar-my-profile',
  NAVBAR_MY_OPPORTUNITIES: 'navbar-my-opportunities',
  NAVBAR_ACCOUNT_SETTINGS: 'navbar-account-settings',
  NAVBAR_SIGN_OUT: 'navbar-sign-out',
  SIGN_IN_FORM_EMAIL: 'sign-in-form-email',
  SIGN_IN_FORM_PASSWORD: 'sign-in-form-password',
  SIGN_IN_FORM_SUBMIT: 'sign-in-form-submit',
  SIGN_UP_FORM_EMAIL: 'sign-up-form-email',
  SIGN_UP_FORM_PASSWORD: 'sign-up-form-password',
  SIGN_UP_FORM_SUBMIT: 'sign-up-form-submit',
};
