/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_STUFF: 'add-stuff',
  ADD_OPPORTUNITY: 'add-opportunity',
  EDIT_STUFF: 'edit-stuff',
  EDIT_OPPORTUNITY: 'edit-stuff',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  LIST_OPPORTUNITY: 'list-opportunity',
  MANAGE_DATABASE: 'manage-database',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  MY_ORGANIZATION_PROFILE: 'my-organization-profile',
  ORGANIZATION_SIGN_UP: 'organization-sign-up',
  ABOUT_US: 'about-us',
  VOLUNTEER_SIGN_UP: 'volunteer-sign-up',
};
