/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_OPPORTUNITY: 'add-opportunity',
  EDIT_MY_PROFILE: 'edit-my-profile',
  EDIT_MY_ORGANIZATION_PROFILE: 'edit-my-organization-profile',
  EDIT_OPPORTUNITY: 'edit-opportunity',
  LANDING: 'landing',
  LIST_OPPORTUNITY: 'list-opportunity',
  MANAGE_DATABASE: 'manage-database',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  MY_ORGANIZATION_PROFILE: 'my-organization-profile',
  MY_PROFILE: 'my-profile',
  MY_BOOKMARKS: 'my-bookmarks',
  ORGANIZATION_SIGN_UP: 'organization-sign-up',
  ABOUT_US: 'about-us',
  VOLUNTEER_SIGN_UP: 'volunteer-sign-up',
  VIEW_OPPORTUNITY: 'view-opportunity',
  OPPORTUNITY_HOURS: 'opportunity-hours',
  CALENDAR_SCHEDULE: 'calendar-schedule',
  BROWSE_OPPORTUNITIES: 'browse-opportunities',
  ORGANIZATION_LIBRARY: 'organization-library',
  VIEW_MAP: 'view-map',
  PASSWORD_CHANGE: 'password-change',
  USERNAME_CHANGE: 'username-change',
};
